version: "3"

services:
  backend: 
    build: 
      context: ./MockS
      dockerfile: Dockerfile
    command: gunicorn DRFpractice.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend