version: "3"

services:
  backend: 
    build: 
      context: ./MockS
    command: gunicorn DRFpractice.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: ./MockF
    ports:
      - "3000:3000"
    volumes:
      - ./MockF:/app
    command: npm start